import ProjectDescription

let destinations: Destinations = [.iPhone, .iPad, .mac]
let deploymentTargets: DeploymentTargets = .multiplatform(iOS: "15.0", macOS: "12.0")

let project = Project(
    name: "Hammer",
    options: .options(
        automaticSchemesOptions: .enabled(codeCoverageEnabled: true),
        developmentRegion: "en",
        disableBundleAccessors: true,
        // Keep the test project separate from projects generated by SwiftPM consumers.
        xcodeProjectName: "HammerTests"
    ),
    settings: .settings(base: [
        "CODE_SIGN_STYLE": "Automatic",
        "CURRENT_PROJECT_VERSION": "1",
        "DEVELOPMENT_TEAM": .string(Environment.developmentTeam.getString(default: "")),
        "MARKETING_VERSION": "1.0",
        "SWIFT_VERSION": "5.0",
    ]),
    targets: [
        .target(
            name: "Hammer",
            destinations: destinations,
            product: .framework,
            bundleId: "com.lyft.Hammer",
            deploymentTargets: deploymentTargets,
            infoPlist: "Sources/Hammer/Info.plist",
            sources: ["Sources/Hammer/**/*.swift"],
            settings: .settings(base: [
                "ENABLE_TESTING_SEARCH_PATHS": "YES",
            ])
        ),
        .target(
            name: "HammerTests",
            destinations: destinations,
            product: .unitTests,
            bundleId: "com.lyft.HammerTests",
            deploymentTargets: deploymentTargets,
            infoPlist: "Tests/HammerTests/Info.plist",
            sources: ["Tests/HammerTests/**/*.swift"],
            dependencies: [
                .target(name: "Hammer"),
                .target(name: "TestHost"),
            ],
            settings: .settings(base: [
                "BUNDLE_LOADER": "$(TEST_HOST)",
                "TEST_HOST": "$(BUILT_PRODUCTS_DIR)/TestHost.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/TestHost",
            ])
        ),
        .target(
            name: "TestHost",
            destinations: destinations,
            product: .app,
            bundleId: "com.lyft.TestHost",
            deploymentTargets: deploymentTargets,
            infoPlist: "TestHost/Info.plist",
            sources: ["TestHost/**/*.swift"],
            resources: [
                .glob(pattern: "TestHost/LaunchScreen.storyboard", inclusionCondition: .when([.ios])),
                .glob(pattern: "TestHost/AppIcon.xcassets", inclusionCondition: .when([.ios])),
            ],
            settings: .settings(base: [
                "GENERATE_INFOPLIST_FILE": "YES",
                "INFOPLIST_FILE[sdk=macosx*]": "",
                "INFOPLIST_KEY_NSPrincipalClass[sdk=macosx*]": "NSApplication",
            ])
        ),
    ],
    additionalFiles: ["README.md", "CONTRIBUTING.md", "Makefile", "mise.toml"],
    resourceSynthesizers: []
)
